// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<int>("StaffDeviceRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("staff_device_revision");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("resource");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Classroom", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LayoutJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("classrooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "UC-101",
                            LayoutJson = "{\"Id\":\"UC-101\",\"Name\":\"U\\u010Dionica 101\",\"Description\":\"Postoje\\u0107i raspored u\\u010Dionice\",\"Width\":8,\"Height\":6,\"Computers\":[{\"Id\":\"1\",\"X\":0.96,\"Y\":1.62},{\"Id\":\"2\",\"X\":2.16,\"Y\":1.62},{\"Id\":\"3\",\"X\":4.4,\"Y\":1.62},{\"Id\":\"4\",\"X\":5.6,\"Y\":1.62},{\"Id\":\"5\",\"X\":6.8,\"Y\":1.62},{\"Id\":\"6\",\"X\":0.96,\"Y\":2.4000000000000004},{\"Id\":\"7\",\"X\":2.16,\"Y\":2.4000000000000004},{\"Id\":\"8\",\"X\":4.4,\"Y\":2.4000000000000004},{\"Id\":\"9\",\"X\":5.6,\"Y\":2.4000000000000004},{\"Id\":\"10\",\"X\":6.8,\"Y\":2.4000000000000004},{\"Id\":\"11\",\"X\":0.96,\"Y\":3.18},{\"Id\":\"12\",\"X\":2.16,\"Y\":3.18},{\"Id\":\"13\",\"X\":4.4,\"Y\":3.18},{\"Id\":\"14\",\"X\":5.6,\"Y\":3.18},{\"Id\":\"15\",\"X\":6.8,\"Y\":3.18},{\"Id\":\"16\",\"X\":0.96,\"Y\":3.96},{\"Id\":\"17\",\"X\":2.16,\"Y\":3.96},{\"Id\":\"18\",\"X\":4.4,\"Y\":3.96},{\"Id\":\"19\",\"X\":5.6,\"Y\":3.96},{\"Id\":\"20\",\"X\":6.8,\"Y\":3.96},{\"Id\":\"21\",\"X\":0.96,\"Y\":4.74},{\"Id\":\"22\",\"X\":2.16,\"Y\":4.74},{\"Id\":\"23\",\"X\":4.4,\"Y\":4.74},{\"Id\":\"24\",\"X\":5.6,\"Y\":4.74},{\"Id\":\"25\",\"X\":6.8,\"Y\":4.74}],\"Sensors\":[{\"Id\":\"S1\",\"X\":0,\"Y\":0,\"Model\":\"ESP32\",\"ReferenceRssi\":-45,\"PathLossExponent\":2.7},{\"Id\":\"S2\",\"X\":8,\"Y\":0,\"Model\":\"ESP32\",\"ReferenceRssi\":-45,\"PathLossExponent\":2.7},{\"Id\":\"S3\",\"X\":4,\"Y\":6,\"Model\":\"ESP32\",\"ReferenceRssi\":-45,\"PathLossExponent\":2.7}],\"Revision\":1}",
                            Revision = 1
                        },
                        new
                        {
                            Id = "UC-202",
                            LayoutJson = "{\"Id\":\"UC-202\",\"Name\":\"Ra\\u010Dunarska sala 202\",\"Description\":\"Postoje\\u0107i raspored u\\u010Dionice\",\"Width\":8,\"Height\":6,\"Computers\":[{\"Id\":\"1\",\"X\":1.44,\"Y\":1.6800000000000002},{\"Id\":\"2\",\"X\":3.2,\"Y\":1.6800000000000002},{\"Id\":\"3\",\"X\":4.96,\"Y\":1.6800000000000002},{\"Id\":\"4\",\"X\":6.72,\"Y\":1.6800000000000002},{\"Id\":\"5\",\"X\":1.44,\"Y\":2.94},{\"Id\":\"6\",\"X\":3.2,\"Y\":2.94},{\"Id\":\"7\",\"X\":4.96,\"Y\":2.94},{\"Id\":\"8\",\"X\":6.72,\"Y\":2.94},{\"Id\":\"9\",\"X\":1.44,\"Y\":4.199999999999999},{\"Id\":\"10\",\"X\":3.2,\"Y\":4.199999999999999},{\"Id\":\"11\",\"X\":4.96,\"Y\":4.199999999999999},{\"Id\":\"12\",\"X\":6.72,\"Y\":4.199999999999999}],\"Sensors\":[{\"Id\":\"S1\",\"X\":0,\"Y\":0,\"Model\":\"ESP32\",\"ReferenceRssi\":-45,\"PathLossExponent\":2.7},{\"Id\":\"S2\",\"X\":8,\"Y\":0,\"Model\":\"ESP32\",\"ReferenceRssi\":-45,\"PathLossExponent\":2.7},{\"Id\":\"S3\",\"X\":4,\"Y\":6,\"Model\":\"ESP32\",\"ReferenceRssi\":-45,\"PathLossExponent\":2.7}],\"Revision\":1}",
                            Revision = 1
                        },
                        new
                        {
                            Id = "LAB-A",
                            LayoutJson = "{\"Id\":\"LAB-A\",\"Name\":\"Laboratorija A\",\"Description\":\"Postoje\\u0107i raspored u\\u010Dionice\",\"Width\":8,\"Height\":6,\"Computers\":[{\"Id\":\"1\",\"X\":1.92,\"Y\":2.04},{\"Id\":\"2\",\"X\":4,\"Y\":2.04},{\"Id\":\"3\",\"X\":6.08,\"Y\":2.04},{\"Id\":\"4\",\"X\":1.92,\"Y\":3.3600000000000003},{\"Id\":\"5\",\"X\":4,\"Y\":3.3600000000000003},{\"Id\":\"6\",\"X\":6.08,\"Y\":3.3600000000000003},{\"Id\":\"7\",\"X\":1.92,\"Y\":4.68},{\"Id\":\"8\",\"X\":4,\"Y\":4.68},{\"Id\":\"9\",\"X\":6.08,\"Y\":4.68}],\"Sensors\":[{\"Id\":\"S1\",\"X\":0,\"Y\":0,\"Model\":\"ESP32\",\"ReferenceRssi\":-45,\"PathLossExponent\":2.7},{\"Id\":\"S2\",\"X\":8,\"Y\":0,\"Model\":\"ESP32\",\"ReferenceRssi\":-45,\"PathLossExponent\":2.7},{\"Id\":\"S3\",\"X\":4,\"Y\":6,\"Model\":\"ESP32\",\"ReferenceRssi\":-45,\"PathLossExponent\":2.7}],\"Revision\":1}",
                            Revision = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("HashId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("hash_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("HashId")
                        .IsUnique();

                    b.HasIndex("LastSeenAt");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DeviceObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<double>("Rssi")
                        .HasColumnType("double precision")
                        .HasColumnName("rssi");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sensor_id");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_id");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("signal_type");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("SessionId", "CapturedAt");

                    b.ToTable("device_observations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset?>("RegistrationExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_expires_at");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("room_id");

                    b.Property<string>("RoomSnapshotJson")
                        .HasColumnType("text")
                        .HasColumnName("room_snapshot_json");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("exam_sessions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.StaffDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RegistrationSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceHash")
                        .IsUnique();

                    b.HasIndex("RegistrationSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("staff_devices", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.WhitelistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_hash");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("StaffDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_device_id");

                    b.Property<string>("StudentRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("student_ref");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("StaffDeviceId");

                    b.HasIndex("SessionId", "DeviceHash");

                    b.ToTable("whitelist_entries", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ExamSession", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Entities.StaffDevice", b =>
                {
                    b.HasOne("Domain.Entities.ExamSession", null)
                        .WithMany()
                        .HasForeignKey("RegistrationSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.WhitelistEntry", b =>
                {
                    b.HasOne("Domain.Entities.StaffDevice", null)
                        .WithMany()
                        .HasForeignKey("StaffDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
